import * as NBAIcons from 'react-nba-logos';

export const teamAbbreviation = {
    "Celtics": <NBAIcons.BOS size={50} />,
    "76ers": <NBAIcons.PHI size={50}  />,
    "Bucks": <NBAIcons.MIL size={50}  />,
    "Cavaliers": <NBAIcons.CLE size={50} />,
    "Knicks": <NBAIcons.NYK size={50} />,
    "Nets": <NBAIcons.BKN size={50} />,
    "Heat": <NBAIcons.MIA size={50} />,
    "Hawks": <NBAIcons.ATL size={50} />,
    "Raptors": <NBAIcons.TOR size={50}/>,
    "Bulls": <NBAIcons.CHI size={50} />,
    "Pacers": <NBAIcons.IND size={50}/>,
    "Wizards": <NBAIcons.WAS size={50}/>,
    "Magic": <NBAIcons.ORL size={50} />,
    "Hornets": <NBAIcons.CHA size={50} />,
    "Pistons": <NBAIcons.DET size={50} />,
    "Mavericks": <NBAIcons.DAL size={50} />,
    "Nuggets": <NBAIcons.DEN size={50}/>,
    "Warriors": <NBAIcons.GSW size={50}/>,
    "Rockets": <NBAIcons.HOU size={50}/>,
    "Clippers": <NBAIcons.LAC size={50} />,
    "Lakers": <NBAIcons.LAL size={50} />,
    "Grizzlies": <NBAIcons.MEM size={50}/>,
    "Timberwolves": <NBAIcons.MIN size={50}/>,
    "Pelicans": <NBAIcons.NOP size={50} />,
    "Thunder": <NBAIcons.OKC size={50} />,
    "Suns": <NBAIcons.PHX size={50}/>,
    "Trail Blazers": <NBAIcons.POR size={50} />,
    "Kings": <NBAIcons.SAC size={50} />,
    "Spurs": <NBAIcons.SAS size={50}/>,
    "Jazz": <NBAIcons.UTA size={50}/>
}
